# Membuat PersistenVolume yang akan digunakan mongo
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: karsajobs-ns
  name: mongo-data-pv

# Menentukan kapasitas sebesar 1Gi dengan akses mode Read-write once, nama Storage Class dengan manual
# dan host path pada /data/db
spec:
  storageClassName: "manual"
  capacity:
    storage: 1Gi
  hostPath:
    path: "/data/db"
  accessModes:
    - ReadWriteOnce

---
# Melakukan Claim Persistent Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: karsajobs-ns
  name: mongo-pvc

spec:
  # mendenisikan kriteria pvc yang akan diclaim
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
