# membuat ConfigMap untuk menyimpan data configurasi mongo
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: karsajobs-ns
  name: mongo-configmap

data:
  # File config akan dimount ke /data/db
  mongo.conf: |
    storage:
      dbPath: /data/db
