apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: karsajobs-ns
  name: mongo
  labels:
    app: mongo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo

  serviceName: mongo
  template:
    metadata:
      namespace: karsajobs-ns
      labels:
        app: mongo

    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017

          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD

          volumeMounts:
            - mountPath: /data/db
              name: mongo-persistent-storage
            - mountPath: /config
              name: mongo-configmap
            - mountPath: /etc/mongo-credentials
              name: mongo-credentials

      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: mongo-configmap
          configMap:
            name: mongo-configmap
            items:
              - key: mongo.conf
                path: mongo.conf
        - name: mongo-credentials
          secret:
            secretName: mongo-credentials
