version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable

jobs:
  lint-dockerfile:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
      
      - run:
          name: Build Docker image
          command: docker build --tag "${IMAGE_TAG1}" .

  test-app:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: Test Docker image
          command: go test -v -short --count=1 $(go list ./...)

workflows:
  version: 2
  test:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile