version: "2.1"
orbs:
  docker: circleci/docker@2.1.4

jobs:
  lint-dockerfile:
    executor: docker/machine
    steps:
      - checkout
      - docker/dockerlint:
          dockerfile: Dockerfile
          treat-warnings-as-errors: true

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t "${IMAGE_TAG2}" .

      - run:
          name: Publish Docker image
          command: |
            echo "${GITHUB_PASS}" | docker login ghcr.io --username "${GITHUB_USERNAME}" --password-stdin
            docker push "${IMAGE_TAG2}"

workflows:
  lint-build-Push-dockerfile:
    jobs:
      - lint-dockerfile
      - build-and-push:
          requires:
            - lint-dockerfile