version: "2.1"
orbs:
  docker: circleci/docker@2.1.4

jobs:
  lint-test-push:
    executor: docker/machine
    steps:
      - checkout
      - docker/dockerlint:
          dockerfile: Dockerfile
          treat-warnings-as-errors: true

      - run:
          command: go test -v -short --count=1 $(go list ./...)

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t "${IMAGE_TAG1}" .

      - run:
          name: Publish Docker image
          command: |
            echo "${GITHUB_PASS}" | docker login ghcr.io --username "${GITHUB_USERNAME}" --password-stdin
            docker push "${IMAGE_TAG1}"

workflows:
  lint-Test-build-Push-dockerfile:
    jobs:
      - lint-test-push
      - build-and-push:
          requires:
            - lint-test-push