# Membuat Deployment untuk aplikasi Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: karsajobs-ns
  name: karsajobs-backend-dp
  labels:
    app: karsajobs

# Membuat replikasi sebanyak 2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: karsajobs

  template:
    metadata:
      namespace: karsajobs-ns
      labels:
        app: karsajobs
    # membuat container dengan nama karsajobs-backend
    spec:
      containers:
        - name: karsajobs-backend
          # Menggunakan image dari github
          image: ghcr.io/harisrahmannst/karsajobs:latest
          ports:
            - containerPort: 8080
          env:
            # mendefinisiakn env APP port dan mongo host
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_ROOT_PASSWORD
