apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: karsajobs-ns
  name: karsajobs-backend-dp
  labels:
    app: karsajobs

spec:
  replicas: 2
  selector:
    matchLabels:
      app: karsajobs

  template:
    metadata:
      namespace: karsajobs-ns
      labels:
        app: karsajobs

    spec:
      containers:
        - name: karsajobs-backend
          image: ghcr.io/harisrahmannst/karsajobs:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_ROOT_PASSWORD
