apiVersion: v1
kind: Service
metadata:
  namespace: karsajobs-ns
  name: karsajobs-ui
  labels:
    app: karsajobs-ui
spec:
  type: NodePort
  selector:
    app: karsajobs-ui
  ports:
    - port: 8000
      targetPort: 8000
