apiVersion: apps/v1
kind: Deployment
metadata:
  # mementukan namespace menggunakan ns karsajobs
  namespace: karsajobs-ns
  # memamai aplikasi
  name: karsajobs-ui
  # membuat label
  labels:
    app: karsajobs-ui

spec:
  #menentukan jumlah replikasi
  replicas: 2
  selector:
    matchLabels:
      # menetukan agar sesuai label
      app: karsajobs-ui

  template:
    metadata:
      namespace: karsajobs-ns
      labels:
        app: karsajobs-ui

    spec:
      containers:
        - name: karsajobs-frontend
          image: ghcr.io/harisrahmannst/karsajobs-ui:latest
          ports:
            - containerPort: 8000
          env:
            - name: VUE_APP_BACKEND
